package com.demounimed.demonstracao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Beneficiario implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Nome")
	private java.lang.String nome;
	@org.kie.api.definition.type.Label("Data de Nascimento")
	private java.util.Date dataNascimento;
	@org.kie.api.definition.type.Label("Sexo")
	private java.lang.String sexo;

	@org.kie.api.definition.type.Label(value = "Idade")
	private java.lang.Integer idade;

	public Beneficiario() {
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.util.Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(java.util.Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	public java.lang.String getSexo() {
		return this.sexo;
	}

	public void setSexo(java.lang.String sexo) {
		this.sexo = sexo;
	}

	public java.lang.Integer getIdade() {
		return this.idade;
	}

	public void setIdade(java.lang.Integer idade) {
		this.idade = idade;
	}

	public Beneficiario(java.lang.String nome, java.util.Date dataNascimento,
			java.lang.String sexo, java.lang.Integer idade) {
		this.nome = nome;
		this.dataNascimento = dataNascimento;
		this.sexo = sexo;
		this.idade = idade;
	}

}