package com.demounimed.demonstracao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Devolutiva implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Mensagem")
	private java.lang.String mensagem;

	@org.kie.api.definition.type.Label(value = "Valor")
	private java.lang.Integer valor;

	public Devolutiva() {
	}

	public java.lang.String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(java.lang.String mensagem) {
		this.mensagem = mensagem;
	}

	public java.lang.Integer getValor() {
		return this.valor;
	}

	public void setValor(java.lang.Integer valor) {
		this.valor = valor;
	}

	public Devolutiva(java.lang.String mensagem, java.lang.Integer valor) {
		this.mensagem = mensagem;
		this.valor = valor;
	}

}